services:
  bot:
    restart: unless-stopped
    build:
      context: ./
    volumes:
      - ./db_data/:/db_data/
      - ./migrations/:/migrations/
      - ./config/:/config/
    env_file:
      - .env